export type IconName =
  | "pixelarticons-check"
  | "pixelarticons-calendar-month"
  | "heroicons-cog-6-tooth-solid"
  | "heroicons-question-mark-circle-solid"
  | "heroicons-chart-bar-solid"
  | "heroicons-exclamation-circle-solid"
  | "mdi-pokeball"
  | "pixelarticons-chevron-right"
  | "pixelarticons-chevron-up"
  | "heroicons-share-solid"
  | "pixelarticons-close"
  | "pixelarticons-chevron-left"
  | "pokemon-sun"
  | "pokemon-moon"
  | "pokeball-filled";
